######################################################################
# Automatically generated by qmake (2.01a) ? 11? 8 02:04:12 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += water.hpp
SOURCES += water.cpp
QT += opengl