######################################################################
# Automatically generated by qmake (2.01a) ? 10? 31 21:55:32 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += net.hpp
SOURCES += net.cpp
QT += opengl