######################################################################
# Automatically generated by qmake (2.01a) ? 10? 27 16:18:21 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl
# Input
HEADERS += mapping.hpp
SOURCES += mapping.cpp
