######################################################################
# Automatically generated by qmake (2.01a) ? 10? 27 01:24:54 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += puzzle.hpp
SOURCES += puzzle.cpp
QT += opengl