######################################################################
# Automatically generated by qmake (2.01a) ? 9? 29 22:12:35 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += puzzle.hpp
SOURCES += puzzle.cpp
