######################################################################
# Automatically generated by qmake (2.01a) ? 11? 18 11:22:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += joint.hpp
SOURCES += joint.cpp
QT += opengl