######################################################################
# Automatically generated by qmake (2.01a) ? 10? 14 01:42:17 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bridge.hpp
SOURCES += bridge.cpp
QT += opengl