######################################################################
# Automatically generated by qmake (2.01a) ? 10? 27 01:24:09 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bridge.hpp
SOURCES += bridge.cpp
QT += opengl