######################################################################
# Automatically generated by qmake (2.01a) ? 11? 18 11:23:03 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bridge.hpp
SOURCES += bridge.cpp
QT += opengl