######################################################################
# Automatically generated by qmake (2.01a) ? 9? 29 23:13:08 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ar.hpp
SOURCES += ar.cpp
