######################################################################
# Automatically generated by qmake (2.01a) ? 10? 21 01:13:03 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ar.hpp
SOURCES += ar.cpp
QT += opengl