######################################################################
# Automatically generated by qmake (2.01a) ? 10? 27 01:23:09 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += complex.hpp
SOURCES += complex.cpp
QT += opengl