######################################################################
# Automatically generated by qmake (2.01a) ? 9? 29 16:48:29 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += physics.hpp
SOURCES += physics.cpp
