######################################################################
# Automatically generated by qmake (2.01a) ? 10? 6 19:46:47 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += physics.hpp
SOURCES += physics.cpp
