######################################################################
# Automatically generated by qmake (2.01a) ? 9? 29 20:52:55 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += physics.hpp
SOURCES += physics.cpp
