######################################################################
# Automatically generated by qmake (2.01a) ? 11? 2 10:03:34 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += physics.hpp
SOURCES += physics.cpp
QT += opengl