######################################################################
# Automatically generated by qmake (2.01a) ? 10? 25 00:27:59 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gesture.hpp
SOURCES += gesture.cpp
QT += opengl