######################################################################
# Automatically generated by qmake (2.01a) ? 10? 13 18:26:47 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += editor.hpp
SOURCES += editor.cpp
QT += opengl